// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./bulk-timer.js')
  await import('./chaos.js')
  await import('./dups.js')
  await import('./firewall.js')
  await import('./peer-join.js')
  await import('./retry-timer.js')
  await import('./swarm.js')

  test.resume()
}
