const peerInfo = require('../lib/peer-info')
const tape = require('tape')

tape('basic peer info', function (assert) {
  const info = peerInfo()

  assert.ok(info.firewalled)
  assert.same(info.priority, 2)
  assert.ok(info.update())
  assert.same(info.priority, 2)
  info.active(true)
  info.active(false)
  assert.same(info.requeue(), 0)
  assert.ok(info.update())
  assert.same(info.priority, 0)
  info.active(true)
  info.connected()
  assert.notOk(info.update())
  info.disconnected()
  info.active(false)
  assert.same(info.requeue(), 0)
  assert.ok(info.update())
  assert.same(info.priority, 5)
  assert.same(info.requeue(), 1)
  assert.ok(info.update())
  assert.same(info.priority, 4)
  assert.same(info.requeue(), 2)
  assert.ok(info.update())
  assert.same(info.priority, 1)
  assert.same(info.requeue(), -1)

  assert.end()
})
